### ISSUE TITLE
Cannot download BASE_BOX

### ISSUE THREAD

**Issue by icassina** [dbroeglin/windows-lab#2]
In Vagrantfile I see:

`$BASE_BOX    = "windows2012r2min-wmf5-virtualbox"`

But a `vagrant up dc01` shows:

`==> dc01: Adding box 'windows2012r2min-wmf5-virtualbox' (v0) for provider: virtualbox
    dc01: Downloading: windows2012r2min-wmf5-virtualbox
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.`

How can I obtain this base box? or should I use another name so vagrant will actually know about it?

Thank you!

**Comment by dbroeglin** [comment]
I cannot publish those images as it would most probably be a violation of the Windows EULA. However, you can easily build an image by using the following project: 
https://github.com/dbroeglin/packer-templates

and entering this command (after installing packer): 

```
packer build -force -only virtualbox-iso vbox-2012r2-wmf5.json
```

For detailed explanations about how the project works you can read Matt Wrock's blog posts: http://www.hurryupandwait.io/blog/creating-a-windows-server-2016-vagrant-box-with-chef-and-packer

If you want the lab to work with the final image you will need some of my changes:
https://github.com/mwrock/packer-templates/compare/master...dbroeglin:master
especially keeping Windows Features in the base box.

However, some might annoy you like 
https://github.com/dbroeglin/packer-templates/commit/5146a13248f842d6e8dae81a4221f306ae379dba which changes the keyboard to Swiss-French layout ;-)

You can customise those to your own preferences. 

Please don't hesitate to contact me if you need more help!

**Comment by dbroeglin** [comment]
FYI, I added a bit of documentation at the bottom of the README: https://github.com/dbroeglin/windows-lab

**Comment by icassina** [comment]
Thank you very much!

**Comment by dbroeglin** [comment]
@icassina were you able to make the build work ? Please feel free to give me some feedback about any issue you might have encountered. I created this lab as an exercise for my own learning. It might not be easily reusable for somebody else. I would be happy to improve it though!

**Comment by icassina** [comment]
I used a published 2012r2 box with "wmf5" preinstalled and it worked fine, but I imagine others might struggle with it in the future for the same reason.
I just needed an environnment to test windows SSO (so I never tested IIS nor NetScaler) and I got it thanks to you! … at least until the base box I'm using will expire, then I'll have to use packer anyway. I'll let you know how it went when I try.
